# Generated by Django 3.0.2 on 2020-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
