# Generated by Django 3.0.2 on 2020-07-25 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20200725_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
